### ISSUE TITLE
[Improvement] Cleanup temp output file '/tmp/q8reducerErr.log' generated by Q8 before query execution, to avoid potential access right issue when running Big-Bench with different spark deployment modes (Spark Standalone, Yarn-Client mode)

### ISSUE THREAD

**Issue by xhao1** [intel-hadoop/Big-Bench#11]
Q8 will generate temp output file '/tmp/q8reducerErr.log'

For spark engine (or for hive engine, while we enable 'Hive on Spark' optimization), if we didn't delete the generated temp output file '/tmp/q8reducerErr.log' after 1 round execution with Yarn-Client mode, and then switch to Spark Standalone mode to run Q8 again, Q8 will fail which is root caused by Permission Denied issue for '/tmp/q8reducerErr.log'. (and vice versa)

So suggest to cleanup temp output file '/tmp/q8reducerErr.log' generated by Q8 before query execution to avoid this issue.

Some more detail error log:
Traceback (most recent call last):
  File "q8_reducer.py", line 24, in <module>
    logging.basicConfig(level=logging.DEBUG, filename='/tmp/q8reducerErr.log')
  File "/usr/lib64/python2.6/logging/__init__.py", line 1402, in basicConfig
15/02/10 06:48:63635 INFO ScriptOperator: ErrorStreamProcessor calling reporter.progress()
Traceback (most recent call last):
  File "q8_reducer.py", line 24, in <module>
    logging.basicConfig(level=logging.DEBUG, filename='/tmp/q8reducerErr.log')
  File "/usr/lib64/python2.6/logging/__init__.py", line 1402, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib64/python2.6/logging/__init__.py", line 827, in __init__
    hdlr = FileHandler(filename, mode)
  File "/usr/lib64/python2.6/logging/__init__.py", line 827, in __init__
    StreamHandler.__init__(self, self._open())
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python2.6/logging/__init__.py", line 846, in _open
  File "/usr/lib64/python2.6/logging/__init__.py", line 846, in _open
    stream = open(self.baseFilename, self.mode)
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/tmp/q8reducerErr.log'
IOError: [Errno 13] Permission denied: '/tmp/q8reducerErr.log'

**Comment by Michael-Frank** [comment]
If we dont have the rights to overwrite the log file (because e.g. user 'hive' created it and user 'spark' tries to overwrite it) we probably dont have to right to delete the file.
Because of this i changed the behavior of q8_reducer.py to create the error log file lazily only when an exception occurs.
I have also changed the log file name to pattern: "/tmp/bigbench_q8_reducer_%Y%m%d-%H%M%S.log"
This will avoid issues with multiple consecutive runs.
If this log file is ever created, something seriously gone wrong but most likley someone tinkered with the query or the python script and changed the input stream format (req: 5 tab separated values).

**Comment by xhao1** [comment]
OK. Thanks for your solution Michael-Frank.
